name: 🚀 Feature Request
description: Suggest an idea, feature, or enhancement
labels: [enhancement]
body:
    - type: markdown
      attributes:
          value: |
              Thank you for submitting a feature request. It helps make BlogFlow better.
              Please try to include as much information as possible.

    - type: textarea
      attributes:
          label: What is the problem this feature would solve?
          description: A clear description of what the problem is.
      validations:
          required: true

    - type: textarea
      attributes:
          label: What is the feature you are proposing to solve the problem?
          description: A clear description of what you want to happen.
      validations:
          required: true

    - type: textarea
      attributes:
          label: What alternatives have you considered?
          description: Any alternative solutions or features you've considered.